# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgmi" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "cf70f4a69dc4f3b97bad10ba0f960d1690dffadc3d0c54804d5cf76cfaf78e10"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "97682df0004dfd70b401ef81f0dde21f836b24478c1a3637dc144feb1d5c3ad1"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3dd2b80b9de228ca3c09142e3010aa3d218c5cd5ed27dede57ddaf47ca3752c4"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "49d1162ecfcdf859ba1d117ece55d379572ca21ba990e038dc4a617e52b5db50"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_linux_arm64.tar.gz"
    end
  end

  name "pgmi"
  desc "PostgreSQL-native deployment driver"
  homepage "https://github.com/vvka-141/pgmi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgmi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgmi"]
    end
  end

  # No zap stanza required

end
