# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgmi" do
  version "0.13.0"

  on_macos do
    on_arm do
      sha256 "316e2db0a938bd76b429a357f5074b93ce20c9affe690e94819e10c58c72ec7b"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa3789a18c79cfbcaac3d91d7d4baf48da5e024f840a81c6faadfe75c993d4b1"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "688743ad0c1f074883d652b4ec045c95216ad4e423888a7ba3d5375dfa85424a"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ca9935da261822ae9346ff6466fb4d7c0d3e8dfff1341e8bf23c779ce5795b7c"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pgmi"
  desc "PostgreSQL-native deployment driver"
  homepage "https://github.com/vvka-141/pgmi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgmi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgmi"]
    end
  end

  # No zap stanza required
end
