# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgmi" do
  version "0.12.1"

  on_macos do
    on_arm do
      sha256 "91035016be409338520ec91b4397ff5648b104fba81697a81793ff8fe83a77dd"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "976916d16e923dd93b5d10f1e4d6ae6748edebc7a417f9658fc339dc2ca7feea"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4d64e78efccc82133904921b419bcec043a07b479a17359aad4b6906c696f920"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "29f2e8d66b6c6b8f4147b368f5c2d7bca5fc374e823bd90f7e2218074b648f31"
      url "https://github.com/vvka-141/pgmi/releases/download/v#{version}/pgmi_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pgmi"
  desc "PostgreSQL-native deployment driver"
  homepage "https://github.com/vvka-141/pgmi"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgmi"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgmi"]
    end
  end

  # No zap stanza required
end
