# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgmi < Formula
  desc "PostgreSQL-native execution fabric for humans and autonomous agents"
  homepage "https://github.com/vvka-141/pgmi"
  version "0.7.1"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vvka-141/pgmi/releases/download/v0.7.1/pgmi_0.7.1_darwin_amd64.tar.gz"
      sha256 "c839b1716421cef08f128590d3976048939164da2699d57368094c5688f67232"

      def install
        bin.install "pgmi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vvka-141/pgmi/releases/download/v0.7.1/pgmi_0.7.1_darwin_arm64.tar.gz"
      sha256 "2b686d76996144388eea1bc19841e4368a567e5d2760fae0502ecebb36ec48a2"

      def install
        bin.install "pgmi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vvka-141/pgmi/releases/download/v0.7.1/pgmi_0.7.1_linux_amd64.tar.gz"
      sha256 "334a69a2e840356533085951ed55f21750e84405c792ec442e4fefd34b0ac144"
      def install
        bin.install "pgmi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vvka-141/pgmi/releases/download/v0.7.1/pgmi_0.7.1_linux_arm64.tar.gz"
      sha256 "dd14dbebc06f42331c69f3ab4bfe3ad9974ded85c3ac333d05812e31e288e16a"
      def install
        bin.install "pgmi"
      end
    end
  end

  test do
    system "#{bin}/pgmi", "--version"
  end
end
